config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, :email, :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    VALID_TEXT_REGEX = /\w+/
    validates :title, format: {with: VALID_TEXT_REGEX},
                length: {in: 10..70}
    validates :body, format: {with: VALID_TEXT_REGEX}
    validate :minimum_word_count
    validates :author, format: {with: VALID_TEXT_REGEX},
              length: {in: 4..30}

    def capitalize_title
        title.split(" ").map do |word|
           word.capitalize 
        end.join(" ")
    end

    def image_url
        return 'https://bikozulu.co.ke/wp-content/uploads/2020/12/baba-740x560.jpg' if photo_url.blank?
        photo_url
    end

    def self.ordered_post
        Post.order("created_at DESC")
    end

    private

    def minimum_word_count
        errors.add(:body, "words cannot be below 10") if body.split.size < 10
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end

    private
     def comment_params
        params.require(:comment).permit(:name, :email, :body)
     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :photo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header>
    <div class = "container">
        <%= image_tag "blog.jpg" , id: "logo" =%>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", posts_path %></li>
                <li><%= link_to "New Post", new_post_path %></li>
                <li><%= link_to "Help", "#"%></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>
  <div class="field">
    <%= form.label :photo_url %>
    <%= form.text_field :photo_url %>
  </div>

  <div class="actions">
   <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<section class="content-area">
<% Post.ordered_post.each do |post| %>
  <div class="card mb-3" style="max-width: 900px;">
  <div class="row">
    <div class="col-md-4">
    <%= image_tag(post.image_url, style: 'max-width: 100%;') %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p><small><%= post.created_at.strftime("%d/%m/%Y") %></small></p>
        <h4 class="card-title"><%= post.capitalize_title%></h4>
        <h6 class="card-author">By <%= post.author%></h6>
        <p class="card-text"><%= post.body%></p>
        <button class="btn btn-outline-success"><%= link_to 'Read More', post%></button>
       
      </div>
    </div>
  </div>
  </div>
  <% end %>
</section>

app/views/posts/new.html.erb
<%= render 'form', post: @post%>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<section class="show-container">

  <p>
    <%= @post.created_at.strftime("%d/%m/%Y") %>
  </p>

  <p>
    <%= @post.title %>
  </p>

  <p>
    <%= @post.author %>
  </p>
  <p>
    <%= @post.body%>
  </p>

  <button class="btn btn-primary-outline"><%= link_to 'Edit', edit_post_path(@post) %></button>
</section>

<section class="comment-container">
<div class="comment-form">
  <p>Leave a Reply</p>
  <p>Your email address will not be published</p>
  <div class="comment-form">
   <%= form_with model: [@post, @post.comments.build] do |form| %>
   <div class="comment-body">
    <%= form.text_area :body, style: 'width: 100%; height: 200px; padding: 20px 20px;'%>
   </div>
   <div class="comment-text">
    <div>
      <%= form.label :name%>
      <%=form.text_field :name, style: 'width: 295px;' %>
    </div>
    <div>
      <%= form.label :email%>
      <%= form.text_field :email , style: 'width: 295px;'%>
    </div>
   </div>
   
   <button class="comment-btn">
    SUBMIT COMMENT
    <%form.submit %>
   </button>
   <% end %>
  </div>
</div>
<div class="comments">
<p><%= pluralize(@post.comments.count, "COMMENT")%></p>

<% @post.comments.each do |comment|%> 
  <p><%= comment.name%> SAYS:</p>
  <p><%= comment.body%></p>
<% end %>
</div>

</section>